export type ExerciseSet = {
  actual_reps: number | null;
  actual_rpe: number | null;
  actual_weight: number | null;
  e1rm: number | null;
  exercise_id: number;
  id: number;
  note: string | null;
  percentage_max: number | null;
  set_number: number;
  target_reps: number | null;
  target_rpe: number | null;
  target_weight: number | null;
  user_id: string;
  workout_id: number | null;
};

export type NewExerciseSet = {
  // this is the same as ExerciseSet except without id
  // id needs to be generated by the backend database
  actual_reps: number | null;
  actual_rpe: number | null;
  actual_weight: number | null;
  e1rm: number | null;
  exercise_id: number;
  note: string | null;
  percentage_max: number | null;
  set_number: number;
  target_reps: number | null;
  target_rpe: number | null;
  target_weight: number | null;
  user_id: string;
  workout_id: number | null;
};
